language: android
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27

  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

script:
   - ./gradlew build connectedCheck
